import Header from "@/component/layout/Header";
import ViewSourceCode from "@/component/layout/ViewSourceCode";
import IconContextProvider from "@/provider/IconContextProvider";
import { Metadata } from "next";
import { ThemeProvider } from "next-themes";
import "./globals.css";

export const metadata: Metadata = {
  title: "John Joshua | Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className="antialiased"
      >
        <ThemeProvider enableSystem={true}>
          <IconContextProvider>

            <ViewSourceCode />
            <div className="relative grid grid-rows-[80px_1fr] min-h-screen">
              <Header />
              <main className="">
                {children}
              </main>
            </div>
          </IconContextProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
