import Header from "@/component/layout/Header";
import ViewSourceCode from "@/component/layout/ViewSourceCode";
import IconContextProvider from "@/provider/IconContextProvider";
import { Metadata } from "next";
import { ThemeProvider } from "next-themes";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider enableSystem={true}>
          <IconContextProvider>

            <ViewSourceCode />
            <div className="relative grid grid-rows-[80px_1fr] min-h-screen">
              <Header />
              <main className="">
                {children}
              </main>
            </div>
          </IconContextProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
